# Generated by Django 5.2 on 2025-06-20 05:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JogadorPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nome_empresa_jogador', models.CharField(blank=True, help_text='Ex: Empresa A, Empresa B...', max_length=50, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada'), ('PAUSADA', 'Pausada')], default='INICIADA', max_length=10)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('max_rodadas', models.PositiveIntegerField(default=7, help_text='Número máximo de rodadas para a partida.')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_admin', to=settings.AUTH_USER_MODEL)),
                ('jogadores', models.ManyToManyField(through='game.JogadorPartida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jogadorpartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partida'),
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('quantidade_demandada', models.PositiveIntegerField(blank=True, null=True)),
                ('destino_demanda', models.CharField(blank=True, max_length=100, null=True)),
                ('resultados', models.JSONField(blank=True, default=dict)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partida')),
                ('produto_demandado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.produto')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('partida', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(help_text='Nome da Unidade/CD, ex: Unidade 1, CD São Paulo', max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('jogador_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='game.jogadorpartida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto')),
            ],
            options={
                'verbose_name': 'Unidade de Estoque',
                'verbose_name_plural': 'Unidades de Estoque',
                'unique_together': {('jogador_partida', 'produto', 'localidade')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='jogadorpartida',
            unique_together={('partida', 'jogador')},
        ),
        migrations.CreateModel(
            name='CustoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa_template', models.CharField(help_text='Ex: Empresa A', max_length=50)),
                ('cd_origem', models.CharField(help_text='Ex: CD São Paulo', max_length=100)),
                ('local_destino', models.CharField(help_text='Ex: Osasco', max_length=100)),
                ('custo_unitario_transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto')),
            ],
            options={
                'verbose_name': 'Custo de Transporte',
                'verbose_name_plural': 'Custos de Transporte',
                'unique_together': {('nome_empresa_template', 'cd_origem', 'local_destino', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='CustoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa_template', models.CharField(help_text='Ex: Empresa A, Empresa B...', max_length=50)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto')),
            ],
            options={
                'verbose_name': 'Custo de Produção',
                'verbose_name_plural': 'Custos de Produção',
                'unique_together': {('nome_empresa_template', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Decisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.PositiveIntegerField(default=0)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('distribuicao', models.JSONField(default=dict)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_decisao', models.DateTimeField(default=django.utils.timezone.now)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_jogador', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_partida', to='game.partida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_rodada', to='game.rodada')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_origem', to='game.unidade')),
            ],
            options={
                'unique_together': {('jogador', 'rodada', 'produto')},
            },
        ),
    ]
