# Generated by Django 5.2 on 2025-05-13 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada'), ('PAUSADA', 'Pausada')], default='INICIADA', max_length=10)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('jogadores', models.ManyToManyField(through='game.JogadorPartida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jogadorpartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partida'),
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rodada', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('decisao_jogadores', models.JSONField(default=dict)),
                ('resultados', models.JSONField(default=dict)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partida')),
            ],
            options={
                'ordering': ['numero_rodada'],
            },
        ),
        migrations.CreateModel(
            name='Decisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('quantidade_produzida', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribuicao', models.JSONField(default=dict)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_decisao', models.DateTimeField(default=django.utils.timezone.now)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partida')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='game.rodada')),
            ],
            options={
                'unique_together': {('jogador', 'rodada', 'produto')},
            },
        ),
    ]
