# Generated by Django 5.2 on 2025-06-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa_template', models.CharField(help_text='Ex: Empresa A, Empresa B...', max_length=50)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto')),
            ],
            options={
                'unique_together': {('nome_empresa_template', 'produto')},
            },
        ),
    ]
