# Generated by Django 5.2 on 2025-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='avanco_automatico',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, a rodada avança assim que o último jogador decide.'),
        ),
    ]
