# Generated by Django 5.2 on 2025-06-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_partida_avanco_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='max_jogadores',
            field=models.PositiveIntegerField(default=4, help_text='Número máximo de jogadores permitidos na partida (1-4).'),
        ),
    ]
