# Generated by Django 5.2 on 2025-06-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_custoproducao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custoproducao',
            options={'verbose_name': 'Custo de Produção', 'verbose_name_plural': 'Custos de Produção'},
        ),
    ]
