# Generated by Django 5.2 on 2025-05-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodada',
            options={'ordering': ['numero']},
        ),
        migrations.RenameField(
            model_name='rodada',
            old_name='numero_rodada',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='rodada',
            name='destino_demanda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='preco_maximo_aceitavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='produto_demandado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodadas_demandadas', to='game.produto'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='quantidade_demandada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decisao',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_jogador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decisao',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_partida', to='game.partida'),
        ),
        migrations.AlterField(
            model_name='decisao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto'),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EstoqueJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('jogador_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.jogadorpartida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.produto')),
            ],
            options={
                'unique_together': {('jogador_partida', 'produto')},
            },
        ),
    ]
